# Generated by Django 4.1.7 on 2023-03-29 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_try', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_test',
            old_name='e_mail',
            new_name='E_Mail',
        ),
        migrations.RenameField(
            model_name='users_test',
            old_name='first_name',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='users_test',
            old_name='last_name',
            new_name='Last_Name',
        ),
    ]
