# Generated by Django 4.1.7 on 2023-03-29 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_try', '0002_rename_e_mail_users_test_e_mail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_test',
            old_name='Last_Name',
            new_name='last',
        ),
        migrations.RenameField(
            model_name='users_test',
            old_name='E_Mail',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='users_test',
            old_name='First_Name',
            new_name='name',
        ),
    ]
