# Generated by Django 4.1.7 on 2023-06-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beitrag',
            name='image',
            field=models.ImageField(null=True, upload_to='static/test'),
        ),
    ]
