# Generated by Django 4.1.7 on 2023-06-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0002_beitrag_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beitrag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/test'),
        ),
    ]
