# Generated by Django 4.1.7 on 2023-04-23 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0004_feedback_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='slug',
        ),
    ]
