# Generated by Django 4.1.7 on 2023-04-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0005_delete_tag_remove_feedback_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
