# Generated by Django 4.1.7 on 2023-04-25 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0006_delete_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
