# Generated by Django 4.1.7 on 2023-05-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0008_beitrag_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beitrag',
            name='author',
        ),
    ]
