# Generated by Django 4.1.7 on 2023-05-18 21:00

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum_app', '0009_remove_beitrag_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='beitrag',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beitrag',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_beitraege', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beitrag',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='titel'),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kommentar', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('beitrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum_app.beitrag')),
            ],
        ),
    ]
